/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-secondary": "#003824",
        "surface-container": "#171f33",
        "on-error-container": "#ffdad6",
        "on-background": "#dae2fd",
        "surface": "#0b1326",
        "surface-tint": "#7bd0ff",
        "outline-variant": "#45464d",
        "on-primary-container": "#008abb",
        "on-error": "#690005",
        "inverse-primary": "#00668a",
        "on-tertiary-container": "#b47300",
        "tertiary": "#ffb95f",
        "primary-fixed-dim": "#7bd0ff",
        "inverse-surface": "#dae2fd",
        "secondary-container": "#00a572",
        "surface-container-high": "#222a3d",
        "on-surface-variant": "#c6c6cd",
        "on-tertiary-fixed": "#2a1700",
        "error-container": "#93000a",
        "surface-variant": "#2d3449",
        "on-tertiary-fixed-variant": "#653e00",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-fixed": "#001e2c",
        "error": "#ffb4ab",
        "on-secondary-fixed": "#002113",
        "surface-container-lowest": "#060e20",
        "secondary-fixed": "#6ffbbe",
        "on-primary-fixed-variant": "#004c69",
        "primary-fixed": "#c4e7ff",
        "secondary": "#4edea3",
        "on-secondary-container": "#00311f",
        "inverse-on-surface": "#283044",
        "background": "#0b1326",
        "surface-dim": "#0b1326",
        "secondary-fixed-dim": "#4edea3",
        "primary-container": "#001a27",
        "surface-container-low": "#131b2e",
        "tertiary-fixed": "#ffddb8",
        "outline": "#909097",
        "on-primary": "#00354a",
        "tertiary-fixed-dim": "#ffb95f",
        "primary": "#7bd0ff",
        "surface-container-highest": "#2d3449",
        "surface-bright": "#31394d",
        "on-tertiary": "#472a00",
        "on-surface": "#dae2fd",
        "tertiary-container": "#251400"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
    },
  },
  plugins: [],
};
